kumuluzee:
  name: nakupovalni-seznami
  version: 1.0.0
  env:
    name: dev
  openapi:
    ui:
      enaled: true
  datasources:
    - jndi-name: jdbc/NakupovalniSeznamDS
      connection-url: jdbc:postgresql://localhost:5432/uporabniki
      username: postgres
      password: postgres
      max-pool-size: 20
  integrations:
    priporocilni-sistemi:
      base-url: http://localhost:8081/v1
  health:
    servlet:
      enabled: true
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/NakupovalniSeznamDS
      disk-space-health-check:
        threshold: 100000000
